name: Build and Lint

on:
  push:
    branches: ["QA"]
  pull_request:
    branches: ["QA"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          npm install
          npm run lint
